id: P010484
initial_creation_type: ocr
source_metadata:
  id: bdr:W23627
  title: གསུང་འབུམ། འཇིགས་མེད་བསྟན་པའི་ཉི་མ།༼བདུད་འཇོམས་རིན་པོ་ཆེའི་དཔེ་མཛོད་ཁང་དུ་བཞུགས་པའི་ཤིང་པར་དང་ལག་བྲིས་འདྲེས་མ།༽
  author: ''
  volumes: {}
