id: I14DADFF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:25:59+00:00'
last_modified: '2022-06-08T13:56:32.431254+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23627
  title: གསུང་འབུམ། འཇིགས་མེད་བསྟན་པའི་ཉི་མ།༼བདུད་འཇོམས་རིན་པོ་ཆེའི་དཔེ་མཛོད་ཁང་དུ་བཞུགས་པའི་ཤིང་པར་དང་ལག་བྲིས་འདྲེས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D2DD:
      image_group_id: I2802
      title: ''
      total_pages: 614
      order: 1
      base_file: D2DD.txt
    D4DA:
      image_group_id: I2803
      title: ''
      total_pages: 568
      order: 2
      base_file: D4DA.txt
    846C:
      image_group_id: I2804
      title: ''
      total_pages: 614
      order: 3
      base_file: 846C.txt
    4E2B:
      image_group_id: I2805
      title: ''
      total_pages: 604
      order: 4
      base_file: 4E2B.txt
    D4D0:
      image_group_id: I2806
      title: ''
      total_pages: 622
      order: 5
      base_file: D4D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
