id: I14DADFF1
legacy_id: P010484
ocr_import_info:
  bdrc_scan_id: W23627
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T06:25:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:20:59.981335+00:00'
last_modified: 2022-09-02 09:21:17.064990
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23627
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23627
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་བསྟན་པའི་ཉི་མ།༼བདུད་འཇོམས་རིན་པོ་ཆེའི་དཔེ་མཛོད་ཁང་དུ་བཞུགས་པའི་ཤིང་པར་དང་ལག་བྲིས་འདྲེས་མ།༽
  author: རྡོ་གྲུབ་ཆེན ༠༣་འཇིགས་མེད་བསྟན་པའི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.9562027762489643
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2806:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2806
      total_pages: 622
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2806.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9547963043881788
    legacy_id: v005
  I2802:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2802
      total_pages: 614
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2802.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9544360975741892
    legacy_id: v001
  I2805:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2805
      total_pages: 604
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2805.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9614151026561575
    legacy_id: v004
  I2803:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2803
      total_pages: 568
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2803.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9534090987237339
    legacy_id: v002
  I2804:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2804
      total_pages: 614
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2804.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.956961333518419
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
